version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-devops-app:
    deploy:
      replicas: 6
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: npm run start

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}